FROM node:10
WORKDIR /app/frontend
ADD . /app/frontend
RUN npm install
EXPOSE 3000
CMD npm run dev


# FROM node:10
# WORKDIR /usr/src/app/frontend
# COPY package*.json ./
# RUN npm install
# EXPOSE 3000
# CMD ["npm", "run", "dev"]
